# Generated by Django 3.1 on 2021-04-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='starttime',
            field=models.DateTimeField(),
        ),
    ]
