# Generated by Django 3.1 on 2021-02-18 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('under_represented_racial_ethnic', models.BooleanField(default=False)),
                ('first_gen_college_student', models.BooleanField(default=False)),
                ('transfer_student', models.BooleanField(default=False)),
                ('lbgtq', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='ally',
            name='area_of_research',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ally',
            name='description_of_research_done_at_lab',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ally',
            name='has_lab_experience',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ally',
            name='hawk_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ally',
            name='how_can_science_ally_serve_you',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ally',
            name='interested_in_being_mentored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ally',
            name='interested_in_connecting_with_other_mentors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ally',
            name='interested_in_joining_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ally',
            name='interested_in_mentoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ally',
            name='interested_in_peer_mentoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ally',
            name='major',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ally',
            name='openings_in_lab_serving_at',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ally',
            name='people_who_might_be_interested_in_iba',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='ally',
            name='user_type',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ally',
            name='willing_to_offer_lab_shadowing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ally',
            name='willing_to_volunteer_for_events',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ally',
            name='works_at',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ally',
            name='year',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AllyStudentCategoryRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ally', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sap.ally')),
                ('student_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sap.studentcategories')),
            ],
        ),
    ]
