# Generated by Django 3.1 on 2021-04-09 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventattendeerelation',
            old_name='attendee',
            new_name='ally',
        ),
        migrations.RenameField(
            model_name='eventinviteerelation',
            old_name='invitee',
            new_name='ally',
        ),
    ]
