# Generated by Django 3.1 on 2021-03-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcategories',
            name='rural',
            field=models.BooleanField(default=False),
        ),
    ]
