# Generated by Django 3.1 on 2021-02-19 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0002_auto_20210218_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ally',
            old_name='iba_ally',
            new_name='user',
        ),
    ]
