# Generated by Django 3.1 on 2021-03-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0002_studentcategories_rural'),
    ]

    operations = [
        migrations.AddField(
            model_name='ally',
            name='interested_in_internship',
            field=models.BooleanField(default=False),
        ),
    ]
