# Generated by Django 3.1 on 2021-02-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0003_auto_20210219_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ally',
            name='user_type',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('ally', 'ALLY')], default='admin', max_length=20),
        ),
    ]
