# Generated by Django 3.1 on 2021-03-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0003_auto_20210219_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcategories',
            old_name='lbgtq',
            new_name='gpa_3',
        ),
        migrations.AddField(
            model_name='studentcategories',
            name='lgbtq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentcategories',
            name='rural_student',
            field=models.BooleanField(default=False),
        ),
    ]
