# Generated by Django 3.1 on 2021-03-05 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0003_ally_interested_in_internship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ally',
            name='interested_in_internship',
        ),
    ]
