# Generated by Django 3.1 on 2021-04-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0003_auto_20210408_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endtime',
            field=models.DateTimeField(default=models.DateTimeField()),
        ),
    ]
