# Generated by Django 3.1 on 2021-03-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0004_auto_20210302_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='ally',
            name='firstName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ally',
            name='lastName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
