# Generated by Django 3.1 on 2021-02-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0004_auto_20210226_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ally',
            name='user_type',
            field=models.CharField(max_length=20),
        ),
    ]
