# Generated by Django 3.1 on 2021-04-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0004_auto_20210408_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endtime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='starttime',
            new_name='start_time',
        ),
    ]
