# Generated by Django 3.1 on 2021-02-24 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0004_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='message',
        ),
    ]
