# Generated by Django 3.1 on 2021-03-06 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0004_remove_ally_interested_in_internship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ally',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='ally',
            name='lastName',
        ),
    ]
