# Generated by Django 3.1 on 2021-03-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0005_auto_20210303_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='ally',
            name='first_gen_college_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ally',
            name='lgbtq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ally',
            name='low_income',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ally',
            name='rural_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ally',
            name='transfer_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ally',
            name='under_represented_racial_ethnic',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AllyStudentCategoryRelation',
        ),
        migrations.DeleteModel(
            name='StudentCategories',
        ),
    ]
