# Generated by Django 3.1 on 2021-03-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0005_auto_20210306_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ally',
            name='people_who_might_be_interested_in_iba',
            field=models.BooleanField(default=False),
        ),
    ]
