# Generated by Django 3.1 on 2021-03-04 05:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0006_auto_20210304_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ally',
            name='first_gen_college_student',
        ),
        migrations.RemoveField(
            model_name='ally',
            name='interested_in_peer_mentoring',
        ),
        migrations.RemoveField(
            model_name='ally',
            name='lgbtq',
        ),
        migrations.RemoveField(
            model_name='ally',
            name='low_income',
        ),
        migrations.RemoveField(
            model_name='ally',
            name='rural_student',
        ),
        migrations.RemoveField(
            model_name='ally',
            name='transfer_student',
        ),
        migrations.RemoveField(
            model_name='ally',
            name='under_represented_racial_ethnic',
        ),
        migrations.AddField(
            model_name='ally',
            name='identity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
        migrations.AddField(
            model_name='ally',
            name='interested_in_mentor_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ally',
            name='willing_to_mentor_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ally',
            name='area_of_research',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
    ]
