# Generated by Django 3.1 on 2021-03-21 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0007_auto_20210315_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventAllyRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ally', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sap.ally')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sap.event')),
            ],
        ),
    ]
