# Generated by Django 3.1 on 2021-03-24 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0008_event_eventallyrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventallyrelation',
            name='ally',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sap.ally'),
        ),
        migrations.AlterField(
            model_name='eventallyrelation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sap.event'),
        ),
    ]
