# Generated by Django 3.1 on 2021-04-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0010_studentcategories_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
