# Generated by Django 3.1 on 2021-04-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0011_auto_20210409_2006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventAllyRelation',
            new_name='EventInviteeRelation',
        ),
    ]
