# Generated by Django 3.1 on 2021-04-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0012_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='num_attending',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='num_invited',
            field=models.IntegerField(default=0),
        ),
    ]
