# Generated by Django 3.1 on 2021-04-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0013_auto_20210413_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='ally',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
