# Generated by Django 3.1 on 2021-04-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0013_auto_20210413_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mentor_status',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='research_field',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='role_selected',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='school_year_selected',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
