# Generated by Django 3.1 on 2021-04-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0013_auto_20210413_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ally',
            name='area_of_research',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
