# Generated by Django 3.1 on 2021-04-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0014_auto_20210419_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invite_all',
            field=models.BooleanField(default=True),
        ),
    ]
