# Generated by Django 3.1 on 2021-04-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0014_ally_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ally',
            name='image_url',
            field=models.CharField(default='https://sepibafiles.blob.core.windows.net/sepibacontainer/blank-profile-picture.png', max_length=500),
        ),
    ]
