# Generated by Django 3.1 on 2021-04-28 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0014_auto_20210427_0503'),
        ('sap', '0016_event_special_category'),
    ]

    operations = [
    ]
