# Generated by Django 3.1 on 2021-04-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0017_merge_20210428_2207'),
        ('sap', '0015_auto_20210428_0023'),
    ]

    operations = [
    ]
