# Generated by Django 3.1 on 2021-04-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0017_merge_20210428_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='ally',
            name='reset_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='allday',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='invite_all',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
