# Generated by Django 3.1 on 2021-05-04 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0019_auto_20210501_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllyMentorRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ally', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ally_mentor_relation', to='sap.ally')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='sap.ally')),
            ],
        ),
        migrations.CreateModel(
            name='AllyMenteeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ally', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ally_mentee_relation', to='sap.ally')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee', to='sap.ally')),
            ],
        ),
    ]
