name: Build and deploy Django app to Azure App Service

on:
  push:
    branches:
      - sandbox

env:
  WEBAPP_NAME: 'sep-team1-iba'  # Replace with the name of your Azure web app

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Setup Python version
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Create and start virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Collect static
      run: python manage.py collectstatic

    - name: Run tests
      run: python manage.py test
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

    - name: Run linter
      run:  pylint --load-plugins pylint_django --django-settings-module=azuresite.settings sap/
